name: ${name}
main: org.primesoft.midiplayer.MidiPlayerMain
version: ${version}
authors: [SBPrime]
api-version: 1.21
description: ${description}
libraries:
  - com.googlecode.json-simple:json-simple:1.1.1
permissions:
  musicplayer.*:
    description: Grants access to all MidiPlayer permissions
    default: op
    children:
      midiplayer.admin.*: true
      midiplayer.playglobal: true
      midiplayer.play: true
  midiplayer.playglobal:
    description: Grants access to play global midi command
    default: op
  midiplayer.admin.*:
    description: Grants access to all MidiPlayer admin permissions
    default: op
    children:
      musicplayer.admin.reload: true
  midiplayer.admin.reload:
    description: Allows you to reload MidiPlayer config
    default: op
